:cachedir: /var/cache/r10k
:sources:
  puppet:
    basedir: /etc/puppetlabs/puppet/environments
    prefix: false
    remote: file:///vagrant/config/environmentsrepo

:purgedirs:
  - /etc/puppetlabs/puppet/environments
